services:
  genjishimada-ocr-dev:
    container_name: genjishimada-ocr-dev
    build:
      context: .
    networks:
      - genji-network
    restart: unless-stopped
    mem_limit: 2.5g


networks:
  genji-network:
    external: true
