services:
  genjishimada-ocr-dev:
    container_name: genjishimada-ocr-dev
    build:
      context: .
    networks:
      - genji-network
    restart: unless-stopped
    resources:
        limits:
          memory: 2.5gb


networks:
  genji-network:
    external: true
