services:
  genjishimada-ocr:
    container_name: genjishimada-ocr
    environment:
      OCR_MKLDNN: "1"
      OCR_CPU_THREADS: "0"
      OCR_MKLDNN_CACHE: "20"
      DISABLE_MODEL_SOURCE_CHECK: "True"
    build:
      context: .
    networks:
      - genji-network
    restart: unless-stopped
    mem_limit: 2.5g

networks:
  genji-network:
    external: true
