[project]
name = "genjishimada-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.128.0",
    "numpy==2.4.1",
    "opencv-python-headless==4.13.0.90",
    "paddleocr==3.3.3",
    "paddlepaddle==3.2.2",
    "pillow==12.1.0",
    "uvicorn[standard]==0.40.0",
    "aiohttp==3.13.3",
]
[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
exclude = ["tests"]
line-length = 120
target-version = "py310"

lint.select = [
    'E',
    'F',
    'W',
    'A',
    'PL',
    'I',
    'SIM',
    'RUF',
    'ASYNC',
    'C4',
    'INP',
    'ERA',
    'SLF',
    'PIE',
    'PYI',
    'ANN',
    'N',
    'D',
]
lint.ignore = [
    'ANN002',
    'ANN003',
    'D203',
    'D100',
    'D101',
    'D104',
    'RUF012',
    'TC002',
    'D213',
    'TC001',
    'PLR2004'
]
[tool.ruff.lint.pydocstyle]
convention = "google"
